UPDATE "Boek" AS boek
SET "naam" = labels."naam"
FROM (VALUES
  ('boek-i', 'I - Algemene beginselen'),
  ('boek-ii', 'II - Organisatorische structuren en sociaal overleg'),
  ('boek-iii', 'III - Arbeidsplaatsen'),
  ('boek-iv', 'IV - Arbeidsmiddelen'),
  ('boek-v', 'V - Omgevingsfactoren en fysische agentia'),
  ('boek-vi', 'VI - Chemische en gevaarlijke agentia'),
  ('boek-vii', 'VII - Biologische agentia'),
  ('boek-viii', 'VIII - Ergonomie en preventie van MSA'),
  ('boek-ix', 'IX - Collectieve bescherming en individuele uitrusting'),
  ('boek-x', 'X - Werkorganisatie en bijzondere werknemerscategorieën')
) AS labels("id", "naam")
WHERE boek."id" = labels."id";

INSERT INTO "Titel" ("id", "boekId", "naam") VALUES
  ('boek-i-titel-1', 'boek-i', '1 - Inleidende bepalingen'),
  ('boek-i-titel-2', 'boek-i', '2 - Algemene beginselen welzijnsbeleid'),
  ('boek-i-titel-3', 'boek-i', '3 - Preventie psychosociale risico’s'),
  ('boek-i-titel-4', 'boek-i', '4 - Gezondheidstoezicht werknemers'),
  ('boek-i-titel-5', 'boek-i', '5 - Eerste hulp'),
  ('boek-i-titel-6', 'boek-i', '6 - Maatregelen bij arbeidsongeval'),
  ('boek-ii-titel-1', 'boek-ii', '1 - Interne preventiedienst'),
  ('boek-ii-titel-2', 'boek-ii', '2 - Gemeenschappelijke interne preventiedienst'),
  ('boek-ii-titel-3', 'boek-ii', '3 - Externe preventiedienst'),
  ('boek-ii-titel-4', 'boek-ii', '4 - Vorming en bijscholing preventieadviseurs'),
  ('boek-ii-titel-5', 'boek-ii', '5 - Externe diensten technische controles'),
  ('boek-ii-titel-6', 'boek-ii', '6 - Laboratoria'),
  ('boek-ii-titel-7', 'boek-ii', '7 - Comités voor preventie en bescherming'),
  ('boek-ii-titel-8', 'boek-ii', '8 - Rechtstreekse participatie'),
  ('boek-ii-titel-9', 'boek-ii', '9 - Hoge Raad voor preventie en bescherming'),
  ('boek-iii-titel-1', 'boek-iii', '1 - Basiseisen arbeidsplaatsen'),
  ('boek-iii-titel-2', 'boek-iii', '2 - Elektrische installaties'),
  ('boek-iii-titel-3', 'boek-iii', '3 - Brandpreventie arbeidsplaatsen'),
  ('boek-iii-titel-4', 'boek-iii', '4 - Explosieve atmosferen'),
  ('boek-iii-titel-5', 'boek-iii', '5 - Opslag ontvlambare vloeistoffen'),
  ('boek-iii-titel-6', 'boek-iii', '6 - Veiligheids- en gezondheidssignalering'),
  ('boek-iv-titel-1', 'boek-iv', '1 - Definities'),
  ('boek-iv-titel-2', 'boek-iv', '2 - Bepalingen voor alle arbeidsmiddelen'),
  ('boek-iv-titel-3', 'boek-iv', '3 - Mobiele arbeidsmiddelen'),
  ('boek-iv-titel-4', 'boek-iv', '4 - Hijsen of heffen van lasten'),
  ('boek-iv-titel-5', 'boek-iv', '5 - Tijdelijke werkzaamheden op hoogte'),
  ('boek-v-titel-1', 'boek-v', '1 - Thermische omgevingsfactoren'),
  ('boek-v-titel-2', 'boek-v', '2 - Lawaai'),
  ('boek-v-titel-3', 'boek-v', '3 - Trillingen'),
  ('boek-v-titel-4', 'boek-v', '4 - Hyperbare omgeving'),
  ('boek-v-titel-5', 'boek-v', '5 - Ioniserende stralingen'),
  ('boek-v-titel-6', 'boek-v', '6 - Kunstmatige optische straling'),
  ('boek-v-titel-7', 'boek-v', '7 - Elektromagnetische velden'),
  ('boek-vi-titel-1', 'boek-vi', '1 - Chemische agentia'),
  ('boek-vi-titel-2', 'boek-vi', '2 - Kankerverwekkende, mutagene en reprotoxische agentia'),
  ('boek-vi-titel-3', 'boek-vi', '3 - Asbest'),
  ('boek-vi-titel-4', 'boek-vi', '4 - Bepalingen voor asbestverwijderaars'),
  ('boek-vii-titel-1', 'boek-vii', '1 - Algemene bepalingen'),
  ('boek-viii-titel-1', 'boek-viii', '1 - Algemene bepalingen'),
  ('boek-viii-titel-2', 'boek-viii', '2 - Beeldschermen'),
  ('boek-viii-titel-3', 'boek-viii', '3 - Manueel hanteren van lasten'),
  ('boek-viii-titel-4', 'boek-viii', '4 - Werkzitplaatsen en rustzitplaatsen'),
  ('boek-ix-titel-1', 'boek-ix', '1 - Collectieve beschermingsmiddelen'),
  ('boek-ix-titel-2', 'boek-ix', '2 - Persoonlijke beschermingsmiddelen'),
  ('boek-ix-titel-3', 'boek-ix', '3 - Werkkledij'),
  ('boek-x-titel-1', 'boek-x', '1 - Nachtarbeiders en werknemers in ploegendienst'),
  ('boek-x-titel-2', 'boek-x', '2 - Uitzendarbeid'),
  ('boek-x-titel-3', 'boek-x', '3 - Jongeren op het werk'),
  ('boek-x-titel-4', 'boek-x', '4 - Stagiairs'),
  ('boek-x-titel-5', 'boek-x', '5 - Moederschapsbescherming'),
  ('boek-x-titel-6', 'boek-x', '6 - Dienstboden en huispersoneel')
ON CONFLICT ("id") DO UPDATE SET
  "boekId" = EXCLUDED."boekId",
  "naam" = EXCLUDED."naam";
